/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_t13max_test_dll_DllTest */

#ifndef _Included_com_t13max_test_dll_DllTest
#define _Included_com_t13max_test_dll_DllTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_t13max_test_dll_DllTest
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_t13max_test_dll_DllTest_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
